namespace TX_Randomizer
{
    public partial class Ammunition
    {
        public enum Name
        {
            None,
            Standard,
            Orange,
            Red,
            Acid,
            SkyBlue,
            Indigo,
            White,
            Thor,
            Papercracker,
            Emerald,
            Shine,
            PaleBlue,
            PaleGreen,
            Purple,
            Gloom,
            Smoke,
            BetaTester,
            Golden,
            Coral,
            Frozen,
            Moon,
            Cannonball,
            Antaeus,
            Frontier,
            Lightning,
            Thermite,
            Dragon,
            Blue,
            Tourquoise,
            Violet,
            AcidRain
        }
    }
}